### ISSUE TITLE
I can't get this to work, any ideas?

### ISSUE THREAD

**Issue by zacps** [warbear0129/QuickTemplate-Syntax-Highlighting-Vim#1]
I don't have a lot of experience with vimscript so I don't really know what to do to troubleshoot. I've checked that it's loaded with `:scriptnames` but that's about it.

**Comment by codelitt** [comment]
@zacps I couldn't get it working either. It's because of how the dir structure is laid out and a missing line for detecting the filetype. I've submitted a PR here https://github.com/warbear0129/vim-qtpl/pull/2 or you can use my fork.
